[phases.setup]
nixPkgs = ['nodejs_22', 'openssl']

[variables]
HUSKY = "0"
NEXT_TELEMETRY_DISABLED = "1"
TURBO_TELEMETRY_DISABLED = "1"

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = [
  "npm run prisma:generate",
  "cd apps/remix && bash .bin/build.sh"
]

[start]
cmd = "npx prisma migrate deploy --schema packages/prisma/schema.prisma && cd apps/remix && NODE_ENV=production node build/server/main.js"